INSERT INTO burgers (burger_name, devoured) VALUES ('Bacon Burgers on Brioche Buns', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Umami Burgers with Port and Stilton', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Pug Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Green-Chile Burgers with Fried Eggs', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Minetta Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Cheddar-and-Onion Smashed Burgers', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Cheddar BLT Burgers with Tarragon Russian Dressing', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Beef Burgers with Peanut-Chipotle Barbecue Sauce', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Chile-Stuffed Cheeseburger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('All-American Hamburgers with Red Onion Compote', false);
